/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as OurProjectsRouteImport } from './routes/our-projects'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutHayatInteriorsRouteImport } from './routes/about-hayat-interiors'
import { Route as IndexRouteImport } from './routes/index'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const OurProjectsRoute = OurProjectsRouteImport.update({
  id: '/our-projects',
  path: '/our-projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutHayatInteriorsRoute = AboutHayatInteriorsRouteImport.update({
  id: '/about-hayat-interiors',
  path: '/about-hayat-interiors',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-hayat-interiors': typeof AboutHayatInteriorsRoute
  '/contact': typeof ContactRoute
  '/our-projects': typeof OurProjectsRoute
  '/services': typeof ServicesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-hayat-interiors': typeof AboutHayatInteriorsRoute
  '/contact': typeof ContactRoute
  '/our-projects': typeof OurProjectsRoute
  '/services': typeof ServicesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-hayat-interiors': typeof AboutHayatInteriorsRoute
  '/contact': typeof ContactRoute
  '/our-projects': typeof OurProjectsRoute
  '/services': typeof ServicesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-hayat-interiors'
    | '/contact'
    | '/our-projects'
    | '/services'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-hayat-interiors'
    | '/contact'
    | '/our-projects'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about-hayat-interiors'
    | '/contact'
    | '/our-projects'
    | '/services'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutHayatInteriorsRoute: typeof AboutHayatInteriorsRoute
  ContactRoute: typeof ContactRoute
  OurProjectsRoute: typeof OurProjectsRoute
  ServicesRoute: typeof ServicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-projects': {
      id: '/our-projects'
      path: '/our-projects'
      fullPath: '/our-projects'
      preLoaderRoute: typeof OurProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-hayat-interiors': {
      id: '/about-hayat-interiors'
      path: '/about-hayat-interiors'
      fullPath: '/about-hayat-interiors'
      preLoaderRoute: typeof AboutHayatInteriorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutHayatInteriorsRoute: AboutHayatInteriorsRoute,
  ContactRoute: ContactRoute,
  OurProjectsRoute: OurProjectsRoute,
  ServicesRoute: ServicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
